package org.vimal.security.v3.enums;

public enum MailType {
    OTP,
    LINK,
    ACCOUNT_DELETION_CONFIRMATION,
    PASSWORD_RESET_CONFIRMATION,
    SELF_PASSWORD_CHANGE_CONFIRMATION,
    SELF_EMAIL_CHANGE_CONFIRMATION,
    SELF_UPDATE_DETAILS_CONFIRMATION,
    SELF_MFA_ENABLE_DISABLE_CONFIRMATION,
    NEW_SIGN_IN_CONFIRMATION
}
